### ISSUE TITLE
UrbanCode Deploy core plugins don't have download link for latest versions.

### ISSUE THREAD

**Issue by pragyadikshit6** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#1]
Some of the core UCD plugins don't have download links for the latest version.
ucd-uDeploy-Version
ucd-uDeploy-Process
ucd-uDeploy-Application
ucd-uDeploy-Resource
ucd-uDeploy-Component
ucd-uDeploy-Environment
ucd-UrbancodeVFS
ucd-uDeployConfigManagement
ucd-FileSystemVersionedSourceConfig

This list is not complete. Please check other plugins as well.

**Steps to reproduce**
1. Navigate to "https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/" and click on "IBM UrbanCode Deploy Process".
2. Click on 'Readme">Downloads
3. View page source code.

**Expected behavior**
Download links should be available for all plugin versions.

**Actual Behaviour**
The download link is missing for 2 of the versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/107843339/174600537-b9a1512b-db46-41d1-a57b-bbcf56730d06.png)

**Comment by osmanburucu** [comment]
should be fixed now
