### ISSUE TITLE
Datapower Documentation - Wrong Version

### ISSUE THREAD

**Issue by a-robben** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#12]
The Datapower UCD plugin documentation is incorrectly proporting version [9.827594](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/datapower/datapower-9.827594.zip) as the latest version when the latest version is  [datapower-v23.eb38543.zip](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/datapower/datapower-v23.eb38543.zip) and can be found on the downloads page.
https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/datapower/downloads.html

This page shows latest version is 23
https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/datapower/overview.html

Links where wrong version is listed.
https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/#ibm-datapower-configuration-manager
https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/datapower/

**Comment by a-robben** [comment]
Created pull request to fix this
https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/15

**Comment by osmanburucu** [comment]
Links to external articles/blogs need update as soon as the new url#s are available
