### ISSUE TITLE
SAP blog not found

### ISSUE THREAD

**Issue by reachsenthilnathan** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#14]
urbancode.com had a blog for SAP deployments. That is missing now.

**Comment by osmanburucu** [comment]
Laurel and I are working on migrating missing blogs to UrbanCode community

**Comment by osmanburucu** [comment]
Now published here:
https://community.ibm.com/community/user/wasdevops/blogs/osman-burucu/2022/08/01/urbancode-for-sap
