### ISSUE TITLE
Typo-ed Blog Post Hashtags

### ISSUE THREAD

**Issue by nhmathis** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#17]
The blog post has two hashtags that are typos. This will affect users/customers ability to search for these blogs.

Blog Link: https://community.ibm.com/community/user/wasdevops/blogs/laurel-dickson-bull1/2022/05/23/urbancodecom-has-migrated-to-the-the-ibm-community 

![image](https://user-images.githubusercontent.com/14111822/177417711-9fc37ea7-8790-4265-a88e-d74a4ffa8e0d.png)

**Comment by nhmathis** [comment]
Specifically `#urbandcode` and `#udc-plugins`.

**Comment by osmanburucu** [comment]
Forwarded to Laurel
