### ISSUE TITLE
Client Advocacy program blog

### ISSUE THREAD

**Issue by reachsenthilnathan** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#2]
This blog https://www.urbancode.com/client-advocacy-program/ does not seem to be migrated to new blog site.

**Comment by osmanburucu** [comment]
please find it here: [IBM UrbanCode Community Blog - Client Advocacy](https://community.ibm.com/community/user/wasdevops/blogs/osman-burucu/2022/07/12/client-advocacy-program)
and post comments there if information is missing.
