### ISSUE TITLE
RTAS Test links are not generated correctly

### ISSUE THREAD

**Issue by vito490** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#293]
**Describe the bug**
After importing RTAS testing run data, the link that is generated is not correct, making the user landing on a blank screen

**To Reproduce**
1. Install velocity
2. Install RTAS Plugin
3. Run a test on RTAS
4. Perform a properly formatted REST call to Velocity plugin endpoint
5. Try to access the test results link generated

**Expected behavior**
The correct page displaying test results.

**Screenshots**

**Desktop (please complete the following information):**
1. Velocity version 4.0.11
2. RTAS plugin version urbancode/ucv-ext-rtas:1.0.22
3. Installation Environment: OpenShift 4.12.21
4. Installation Method: Helm Charts generated by velocity online installer

**Additional context**
As far as i can investigate, the problem the test url is the following: the url generated by the velocity plugin is the following

https://RTAS_SERVER_URL/#/project/PROJECT_ID/analyze/results/TEST_EXECUTION_RESULTS_ID

while, to visualize the same test execution results id from the correct project, the url should be formatted like this

https://RTAS_SERVER_URL/#/TEAM_SPACE_URL_ALIAS/project/PROJECT_ID/analyze/results/TEST_EXECUTION_RESULTS_ID

So, if i manually add the team space url alias before the /proejct part of the url, it works correctly. Therefore, team space url alias misses from the generated url. 

Screenshots examples

My Value Stream
![Screenshot 2023-07-10 123644](https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/assets/33374688/69c49868-6342-4df9-b16c-760522e01a16)

The wrong url opened upon clicking on test record under "code metrics and approval" section of the issue
![Screenshot 2023-07-10 123745](https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/assets/33374688/d0f82f72-c418-448e-aa84-5da2f8edbb3d)

The correct url with the /Initial team space url alias added before /project 
![Screenshot 2023-07-10 123859](https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/assets/33374688/9faed93a-51a0-4d2e-ba2e-be0e59fa33ef)

**Comment by osmanburucu** [comment]
Have you checked with latest RTAS plug-in? The latest version 1.0.34 should have fixed the URL issue
