### ISSUE TITLE
Upgrading UCD 7 blog is missing

### ISSUE THREAD

**Issue by reachsenthilnathan** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#3]
https://www.urbancode.com/2019/03/06/white-paper-upgrading-to-urbancode-deploy-7/ 

This blog from urbancode.com is missing in the new blog site

**Comment by osmanburucu** [comment]
File has been uploaded into the library and can be found here: [Upgrading to UrbanCode Deploy 7](https://community.ibm.com/community/user/wasdevops/viewdocument/upgrading-to-urbancode-deploy-7?CommunityKey=9adfe6b6-2e23-4895-8b27-38b93b5e152c&tab=librarydocuments)
