### ISSUE TITLE
Links on https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/WebSphereConfiguration/usage.html are pointing to old website

### ISSUE THREAD

**Issue by arnolddk** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#4]
**Describe the bug**
all links in the documentation on
https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/WebSphereConfiguration/usage.html
are pointing to www.urbancode.com  and are useless, I can not access any documentation at least for this plugin

**To Reproduce**
1. Go to https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/WebSphereConfiguration/usage.html
2. Click on "[Getting started with managing WebSphere Application Server configurations](https://www.urbancode.com/resource/getting-started-with-managing-websphere-application-server-configurations/)"
3. See error

**Expected behavior**
functional documentation

I know this is no technical bug  - but I don't know how I could place the requirement elsewhere

**Comment by osmanburucu** [comment]
Thank You, will check where the new location of the links should be and fix them asap

**Comment by osmanburucu** [comment]
Updated depreciated urbancode.com links in usage.md with migrated articles/blogs on IBM Communities
