### ISSUE TITLE
latest IBM-MQ plugin missing

### ISSUE THREAD

**Issue by dustin1530** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#433]
When attempting to download the [IBM-MQ plugin](https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/blob/main/docs/UCD/WebSphereMQ/README.md) for version [13.1154095](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/WebSphereMQ/ucd-WebSphereMQ-13.1154095.zip) the following error is presented, "404: Not Found" downloading the previous version works as expected.

**Comment by osmanburucu** [comment]
fixed
