### ISSUE TITLE
log4j vulnerability in JBoss plugin

### ISSUE THREAD

**Issue by dyadav23** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#53]
**Describe the bug**
JBoss Application Server UCD Plugin v23 still has log4j jar 1.2.16. Since log4j 1.x is no longer supported it is coming as a vulnerability in Nessus security scan.

**To Reproduce**
Check for version in log4j.jar.

**Expected behavior**
It should be at least upgraded to use log4j v2.17.1

**Comment by osmanburucu** [comment]
Thank You for your input, will check with development team how and when this can be adressed.

**Comment by osmanburucu** [comment]
has been closed with version 24 of plugin
