### ISSUE TITLE
404 received on Salesforce plugin README

### ISSUE THREAD

**Issue by micheless** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#6]
When going to the README for the Salesforce plugin, I get a 404:

https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/SalesForce/README.md

**Comment by osmanburucu** [comment]
The correct Plugin link is here: 
https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/salesforce/README.md

The other Salesforce Plugin entry is a broken duplicate. Will be removed ASAP
