### ISSUE TITLE
Both OpenShift (Source plugin) and "OpenShift for IBM UrbanCode Deploy" (Automation plugin) point to the same file

### ISSUE THREAD

**Issue by micheless** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#7]
UrbanCode Deploy has both a Source Configuration plugin and Automation plugin for OpenShift.  Both the OpenShift (Source plugin) and "OpenShift for IBM UrbanCode Deploy" (Automation plugin) are pointing to the same file which appears to be the Source Configuration File.  We need the Automation one also to be available.

**Comment by osmanburucu** [comment]
Fixed
