### ISSUE TITLE
Broken tables for Steps in "WebSphere Application Server - Deployment" plugin

### ISSUE THREAD

**Issue by micheless** [UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD#77]
Under the "Steps",  the parameter tables are missing their formatting so they are unreadable/unusable.

**Comment by micheless** [comment]
Hi,

The tables don't seem to have changed.  Please check here:  https://urbancode.github.io/IBM-UCx-PLUGIN-DOCS/UCD/Websphere/steps.html

Thanks!

**Comment by osmanburucu** [comment]
strange.. will check
